name: Viam Build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  viam-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Viam Build"
          echo "Version: ${{ github.ref_name }}"
          echo "Ref: ${{ github.sha }}"
          echo "Key ID: ${{ secrets.viam_key_id }}"
          echo "Key Value: ${{ secrets.viam_key_value }}"
      - uses: viamrobotics/build-action@v1
        with:
          version: ${{ github.ref_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
